fixed some obvious mistakes...

diff --git a/cupswatcher b/cupswatcher
--- a/cupswatcher
+++ b/cupswatcher
@@ -15,7 +15,10 @@
 CUPSWATCHER_PATH=/usr/local/sbin/
 TIMER=30
 LAUNCHD_PATH=/Library/LaunchDaemons/com.aapps.cupswatcher
+CUPS_LAUNCHD="/System/Library/LaunchDaemons/org.cups.cupsd.plist"
+
 OSKERN=`sysctl -n kern.ostype`
+LOG_FILE="/var/log/cupswatcher.log"
 
 case "$1" in
 
@@ -48,15 +51,28 @@ case "$1" in
 ##### otherwise continue
 	*)
 
+_reload_cups(){
+	launchctl unload ${CUPS_LAUNCHD}
+	sleep 2
+	launchctl load ${CUPS_LAUNCHD}
+	exit 1
+}
+
 ### run an extra routine if this is a server
 if [ "$1" ==  "-s" ]; then 
-	CUPS_LAUNCHD="/System/Library/LaunchDaemons/org.cups.cupsd.plist"
-	SERVER_STATUS=$(curl --silent http://127.0.0.1:631/printers/ | grep -c -w 'Internal Server Error')
-	echo This is $SERVER_STATUS
-	if [ $SERVER_STATUS -gt 0 ]; then 
-		launchctl unload ${CUPS_LAUNCHD}
-		launchctl unload ${CUPS_LAUNCHD}
-		echo The Server was restarted on $(date) due to an Internal Error >> $LOG_FILE
+	SERVER_STATUS=$(curl --silent http://127.0.0.1:631/printers/)
+	RC=$?
+	
+	if [ $RC -gt 0 ]; then
+		echo -e "The Server was restarted on $(date) due to a Print Server Crash" >> $LOG_FILE
+		_reload_cups
+	
+	else
+		PRINTER_ERROR=`echo $SERVER_STATUS | grep -c -w 'Internal Server Error'`
+		if [ $PRINTER_ERROR -gt 0 ]; then 
+			echo -e "The Server was restarted on $(date) due to an Printer Avaliability Error" >> $LOG_FILE
+			_reload_cups
+		fi
 	fi
 fi
 
@@ -64,9 +80,8 @@ fi
 #### set up varibles
 ENABLE_PRINTER="$(which cupsenable)"
 CANCEL_LAST_JOB="$(which lprm) -P"
-LOG_FILE=/var/log/cupswatcher.log
 
-[[ -z "LOG_FILE" ]] && touch $LOG_FILE && chown root:admin $LOG_FILE && chmod 750 $LOG_FILE 
+[[ -z "$LOG_FILE" ]] && touch $LOG_FILE && chown root:admin $LOG_FILE && chmod 750 $LOG_FILE 
 
 ### Find any paused printers
 PAUSED_PRINTER_LIST=$(lpstat -p | grep disabled | awk '{printf $2 " "}')
